#Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
#SPDX-License-Identifier: BSD-3-Clause-Clear
interface=wlan0
country_code=US
driver=nl80211
ctrl_interface=/var/run/hostapd
ctrl_interface_group=radio
ssid=QSoftAP_6G
acs_exclude_dfs=0

ht_capab=[SHORT-GI-20][SHORT-GI-40][SHORT-GI-80][SHORT-GI-160][HT40+]
#vht_oper_chwidth=0
#he_oper_chwidth=2
ieee80211n=1
ieee80211ac=1
ieee80211ax=1
he_bss_color=35
he_su_beamformer=1
he_su_beamformee=1
he_mu_beamformer=0
he_twt_required=0
ignore_broadcast_ssid=0
wowlan_triggers=any
#ocv=2
beacon_prot=1
##6GHE320####
#op_class=137
#channel=65
#vht_oper_chwidth=9
#he_oper_chwidth=9
#eht_oper_chwidth=9
#he_oper_centr_freq_seg0_idx=63
#eht_oper_centr_freq_seg0_idx=63
##6GHE160####
hw_mode=a
op_class=134
channel=37
he_oper_centr_freq_seg0_idx=47
#channel=65
#he_oper_centr_freq_seg0_idx=79
##6GHE80####
#hw_mode=a
#op_class=133
#channel=37
#he_oper_centr_freq_seg0_idx=39
##5GHE160####
#hw_mode=a
#channel=36
##5GHE80####
#hw_mode=a
#channel=36
##2GHE40####
# hw_mode=g
# channel=1

wpa=2
wpa_pairwise=CCMP
#wpa_group_rekey=600
ieee80211w=2
wpa_key_mgmt=SAE
sae_password=12345678
sae_pwe=2

