# Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

interface=wlan0
country_code=US
driver=nl80211
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
ssid=chan33_160M
acs_exclude_dfs=0
ht_capab=[SHORT-GI-20][SHORT-GI-40][SHORT-GI-80][SHORT-GI-160][HT40+]
ieee80211n=1
ieee80211ax=1
ieee80211ac=1
ieee80211ax=1
ieee80211be=1
he_bss_color=35
he_su_beamformer=1
he_su_beamformee=1
he_mu_beamformer=0
he_twt_required=0
ignore_broadcast_ssid=0
wowlan_triggers=any

#ocv=2
beacon_prot=1
##6GHE160####
hw_mode=a
op_class=134
channel=33
he_oper_centr_freq_seg0_idx=47
eht_oper_centr_freq_seg0_idx=47
eht_oper_chwidth=2

wpa=2
wpa_key_mgmt=SAE
wpa_pairwise=CCMP
sae_password=12345678
ieee80211w=2
sae_pwe=2

