#Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause-Clear
ctrl_interface=/var/run/wpa_supplicant
#update_config=1
device_name=Dida
manufacturer=QCA
model_name=McK
device_type=1-0050F204-1
config_methods=virtual_display keypad virtual_push_button
p2p_no_group_iface=1
